### ISSUE TITLE
 Non-resolvable parent POM

### ISSUE THREAD

**Issue by Somrajgautam** [hendisantika/springboot-dropdown-example#1]
Project build error: Non-resolvable parent POM for com.hendisantika:springboot-dropdown-example:0.0.1-
 SNAPSHOT: Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:2.4.0.RELEASE in central 
 (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at no local POM

**Comment by hendisantika** [comment]
Use Spring Boot 2.3.4.RELEASE version.2.3.4.RELEASE version.
I use 2.4.0.RELEASE version, so I don't need to update very soon.
